### ISSUE TITLE
make transmutable a new repo

### ISSUE THREAD

**Issue by evnix** [hex13/enter-ghost#10]
Transmutable is extremely helpful to me. 
I can't stand ImmutableJS and others with their lengthy verbose syntax.
Transmutable is perfect!!
A new repo for it seems like a good idea to me.

**Comment by hex13** [comment]
> A new repo for it seems like a good idea to me.

This organization code (one big Git repo with many individual npm pacakages) was made on purpose. It's monorepo:
https://github.com/babel/babel/blob/master/doc/design/monorepo.md
https://danluu.com/monorepo/

**Comment by hex13** [comment]
I think this may be not such a bad idea after all. This repo has only 10 stars despite the interest many people have in Transmutable. I suppose maybe even somebody likes Transmutable maybe they don't want to star something which is called `enter-ghost` and is `monorepo of various tools`.

So maybe I should move it to a new repo, for making more clear what project is this?

**Comment by hex13** [comment]
TIL: there is a special command in Git for such things: `git filter-branch`:
http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

https://git-scm.com/docs/git-filter-branch

**Comment by hex13** [comment]
ok, done. Now `transmutable` is here: https://github.com/hex13/transmutable
