### ISSUE TITLE
Array pushing fails

### ISSUE THREAD

**Issue by markerikson** [hex13/enter-ghost#12]
Trying to push into an array fails with an error.

Sample code:

```js
import {transform} from "transmutable";

const original = {
  cow: 123,
  dogs: {
    muchWow: 1,
    names : ["Spot", "Ruff"]
  }
};

const copy = transform(original, t => {
  t.dogs.muchWow = 2;
  t.dogs.names.push("Fluffy");
});

console.log(original);
console.log(copy);
console.log(copy.dogs.names === original.dogs.names);
```

Resulting error:

```
TypeError
curr is undefined

get
transmutable/dist/transmutable.js:15:38
isDirty
transmutable/dist/transmutable.js:34:17
copy
transmutable/dist/transmutable.js:45:14
copy
transmutable/dist/transmutable.js:61:25
copy
transmutable/dist/transmutable.js:61:25
cloneDeepWithDirtyChecking
transmutable/dist/transmutable.js:68:12
reify
transmutable/dist/transmutable.js:133:18
```

Runnable CodeSandbox example: https://codesandbox.io/s/6lxq0z7mk3

It looks like the `.push("Fluffy")` operation is getting turned into two modifications.  One tries to set `[2] = "Fluffy"`, and the other tries to set `.length = 3`.  However, the loop inside `get()` is coming up with an undefined value for `curr`:

```js
function get(target, path) {
  let curr = target, i;
  for (i = 0; i < path.length - 1; curr = curr[path[i++]]);
  if (curr) return curr[path[i]];
}
```

**Comment by hex13** [comment]
Thanks for such thorough analysis. I managed to fix this by checking if curr exists:
https://github.com/hex13/enter-ghost/commit/850ab8ae9e16a197021f94449ee073118d7a1bcf#diff-1fefbcba1bc6d02a68ee5f020f9cfacdR12
