### ISSUE TITLE
Failed to minify transmutable

### ISSUE THREAD

**Issue by tomasz89nowak** [hex13/enter-ghost#9]
I tried to use transmutable with Create React App (1.0.11, it uses webpack version 3.5.1), but production build process throws an error:

```Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 ./node_modules/transmutable/transmutable.js:5 
npm ERR! (...)
```
The problem only occurs with transmutable, deleting and reinstalling node_modules did not work.
Not-minified code is valid and app works.
I'm not sure it's a problem with transmutable, CRA or webpack uglify plugin.
Any clues?

**Comment by hex13** [comment]
As far as I remember Uglify had some issues with ES6 syntax. Maybe I should export transpiled version of my library.

**Comment by hex13** [comment]
Now it exports version with transpiled ES6 syntax to ES5 (worth noting: It's still relies on ES6 Proxies), so it's should compile now.
